spring:
  # datasource 数据源配置内容，对应 DataSourceProperties 配置属性类
  datasource:
    singapo:
        url: jdbc:oracle:thin:@192.168.12.93:1521:orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: JNT_SG
        password: JNT_SG2019
        hikari:
          minimum-idle: 10 # 池中维护的最小空闲连接数，默认为 10 个。
          maximum-pool-size: 10 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。
    taiguo:
        url: jdbc:oracle:thin:@192.168.12.93:1521:orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: JNT_TH
        password: JNT_TH2019
        # HikariCP 自定义配置，对应 HikariConfig 配置属性类
        hikari:
          minimum-idle: 15 # 池中维护的最小空闲连接数，默认为 10 个。
          maximum-pool-size: 10 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。


